Class {
	#name : #TestStepDefinitions,
	#superclass : #ScenarioStepDefinition,
	#category : #'Scenarios-Tests'
}

{ #category : #steps }
TestStepDefinitions >> featureWithOneScenario [
<Given: 'A feature with one scenario'>
]

{ #category : #steps }
TestStepDefinitions >> runTheScenario [

	<When: 'The feature is run'>
	
]

{ #category : #steps }
TestStepDefinitions >> verifyTheSteps [

	<Then: 'The scenario steps get verified'>
	
]
